#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}'

branches:
  except:
    - docs

skip_tags: true
skip_non_tags: false
max_jobs: 1
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\chailove

# scripts that run after cloning repository
install:
  - git submodule update --init

build_script:
  - cmake --use-stderr --target all
