# ChaiLove Appveyor Configuration
# https://ci.appveyor.com/project/RobLoach/libretro-chailove
version: '{build}'

# Build branches master and dev
# The others are done via Pull Requests
branches:
  only:
  - master
  - dev

skip_tags: true
skip_non_tags: false

image: Visual Studio 2017

environment:
  CC: gcc.exe
  TARGET: chailove_libretro.dll
  platform: win
  system_platform: win
  appveyor: 1

init:
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - copy c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\mingw32-make.exe c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\make.exe
  - cmd: set PATH=%PATH%;c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  - path

before_build:
  - make --version
  - gcc --version

build_script:
  - make appveyor=1 system_platform=win

# TODO: Add automated testing
#before_test:
#  - make vendor/noarch/noarch
#
#test_script:
#  - make unittest
