#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}'

branches:
  except:
    - docs

skip_tags: true
skip_non_tags: false

image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

cache:
  - vendor

# scripts that run after cloning repository
install:
  - git submodule update --init
  - cmd: set PATH=%PATH%;C:\MinGW\bin

build_script:
  - minw32-make
