name: Build
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install cmake time g++-7 gcc-7 binutils libc6 python

    - name: Build
      run: |
        ./configure
        make test
